#!/bin/sh

JACK=$YC20_TOOL_PATH"/jack-1.9.6"
JACK_INST=$YC20_TOOL_PATH"/jack-1.9.6/installation"
GTK=$YC20_TOOL_PATH"/gtk"

GTK_COMPONENTS="atk-1.0 cairo freetype2 glib-2.0 gtk-2.0 libpng14 pango-1.0 gdk-pixbuf-2.0"
GTK_COMPONENTS2="glib-2.0 gtk-2.0"

if [ "$1" = "--cflags" ]; then
	for A in "$@"; do

		if [ "$A" = "jack" ]; then
			echo -I$JACK/jack-1.9.6/common
		elif [ "$A" = "gtk+-2.0" ]; then
			echo -n "-mms-bitfields "
			for C in $GTK_COMPONENTS; do
				echo -n -I$GTK/include/$C" "
			done
			for C in $GTK_COMPONENTS2; do
				echo -n -I$GTK/lib/$C/include" "
			done
		elif [ "$A" = "cairo" ]; then
			echo -n "-I"$GTK"/include/cairo "
			echo -n "-I"$GTK"/include/freetype2 "
			echo -n "-I"$GTK"/include "
			echo -n "-I"$GTK"/include/libpng14 "
		fi

	done

elif [ "$1" = "--libs" ]; then
	for A in "$@"; do

		if [ "$A" = "jack" ]; then
			echo -n -ljack -L$JACK_INST"/lib ";
		elif [ "$A" = "gtk+-2.0" ]; then
			echo -n -L$GTK/lib -lgtk-win32-2.0 -lgdk-win32-2.0 -latk-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangowin32-1.0 -lgdi32 -lpango-1.0 -lcairo -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lintl" ";
		elif [ "$A" = "cairo" ]; then
			echo -n -L$GTK/lib -lcairo" "
		fi

	done

fi

echo "";

