#!/bin/sh

JACK="/home/v2/dev/mine/win32/jack-1.9.6"
JACK_INST="/home/v2/dev/mine/win32/jack-1.9.6/installation"
GTK="/home/v2/dev/mine/win32/gtk"

#GTK_COMPONENTS="gdk-pixbuf-2.0 pixman-1 cairo fontconfig libpng14 gtk-2.0 gail-1.0 glib-2.0 atk-1.0 pango-1.0 freetype2"
GTK_COMPONENTS="atk-1.0 cairo freetype2 glib-2.0 gtk-2.0 libpng14 pango-1.0 gdk-pixbuf-2.0"
GTK_COMPONENTS2="glib-2.0 gtk-2.0"

if [ "$1" = "--cflags" ]; then
	for A in "$@"; do

		if [ "$A" = "jack" ]; then
			echo -I$JACK/jack-1.9.6/common
		elif [ "$A" = "gtk+-2.0" ]; then
			echo -n "-mms-bitfields "
			for C in $GTK_COMPONENTS; do
				echo -n -I$GTK/include/$C" "
			done
			for C in $GTK_COMPONENTS2; do
				echo -n -I$GTK/lib/$C/include" "
			done
		fi

	done

elif [ "$1" = "--libs" ]; then
	for A in "$@"; do

		if [ "$A" = "jack" ]; then
			echo -n -ljack -L$JACK_INST/lib" ringbuffer.o ";
		elif [ "$A" = "gtk+-2.0" ]; then
			echo -n -L$GTK/lib -lgtk-win32-2.0 -lgdk-win32-2.0 -latk-1.0 -lgio-2.0 -lgdk_pixbuf-2.0 -lpangowin32-1.0 -lgdi32 -lpango-1.0 -lcairo -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lintl" ";
		fi

	done

fi

echo "";

